### PR TITLE
add document

### PR DESCRIPTION
**Pull request by EXetoC**

### CODE REVIEW

**Comment by flaviut** [comment]
Using macros and templates isn't a language feature on it's own, I think it'd be better if this was mixed into the OOP macro document, around line 161-162.

**Comment by EXetoC** [comment]
Does that not also apply to that particular document? But ok.

**Comment by flaviut** [comment]
> Wouldn't it make sense to just call it "macros" then?
Yep, I was thinking that while reading over this PR.

> And I personally prefer examples that are highly specific.
That's a good idea, but my goal in the  Macros section is to teach people how to approach the creation of a macro mentally.

**Comment by EXetoC** [comment]
The intent was to only show the difference between using getAst and not using getAst. Do you think it's possible to do that if it's introduced in that macro? If you even agree with that approach, but I think it clearly demonstrates what the benefits are.

**Comment by flaviut** [comment]
Looks like it, see

```nim
import macros

macro test(val: expr): stmt =
    template test(v) =
        echo(v + 1)
    
    result = newStmtList(getAst(test(val)))
    echo(repr(result))

test 2
```
```
3

  echo(2 (system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|system.+|...)
      1)
```

**Comment by EXetoC** [comment]
It's less clear, that's all

**Pull request closed without merging**
